apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grade-submission-portal-ingress
  namespace: grade-submission
spec:
  ingressClassName: nginx
  rules:     
  - http: # this rule accepts gtrafic from any host(localhost, blabla.com)
      paths:
      - pathType: Prefix
        path: "/" # any path   => any host, any path
        backend:
          service:
            name: grade-submission-portal
            port: 
              number: 5001
